#!/bin/bash
clear
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e "\033[0;35m"
echo " :;:;:;:;:; :;:;:;:;:;         :;:;      :;:     :;:;:     :;:;:;:;:;:    :;:;:;:;:; "; 
echo " :+:     +: :+:                :+::+:    :+:   :+:   :+:   :+:       :+:  :+:        ";
echo " +;+     :+ +;+                +;+ +;+   +;+ +;+      +;+  +;+        +;+ +;+        ";
echo " +#:+#:+#:  +#:        #=#=#=# +#:  +#:  +#: +#:       +#: +#:        +#: +#:+#:+#:+ ";
echo " #+#     +# #+#                #+#   #+# #+#  #+#     #+#  #+#       #+#  #+#        ";
echo " +#+     #+ +#+                +#+    +#+#+    +#+   +#+   +#+      +#+   +#+        ";
echo " #########  ##########         ###     ####      #####     ##########     ########## ";
echo -e "\e[0m"

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++" 

echo -e '\e[27mGarapan :\e[25m' Register Deinfra Testnet
echo -e '\e[27mAuthor :\e[25m' BeritaCryptoo
echo -e '\e[27mTelegram Channel :\e[25m' @BeritaCryptoo
echo -e '\e[27mTelegram Group :\e[25m' @BeritaaCryptooGroup
echo -e '\e[27mTwitter :\e[25m' @BeritaCryptoo
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"

sleep 2
