#!/bin/bash
echo -e "\033[0;31m"
echo " Y88b   d88P  .d8888b.   .d88888b.  888b    888  .d8888b.  "
echo "  Y88b d88P  d88P  Y88b d88P" "Y88b 8888b   888 d88P  Y88b "
echo "   Y88o88P   Y88b.      888     888 88888b  888 Y88b.      "
echo "    Y888P      Y888b.   888     888 888Y88b 888   Y888b.   "
echo "    d888b         Y88b. 888     888 888 Y88b888      Y88b. "
echo "   d88888b          888 888     888 888  Y88888        888 "
echo "  d88P Y88b  Y88b  d88P Y88b. .d88P 888   Y8888 Y88b  d88P "
echo " d88P   Y88b   Y8888P     Y88888P   888    Y888   Y8888P   "
echo -e "\e[0m"                                                          
                                                          
                                                          
